/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaUsuario;

import Clases.Medico;
import Clases.Usuario;
import Modelo.Registrar_Informe;
import Vista.Vista_Principal;
import java.awt.Image;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class Equipo_Medico extends javax.swing.JFrame {
    private Connection conn;
    private Usuario user;
    /**
     * Creates new form Equipo_Medico
     */
    public Equipo_Medico(Connection conn, Usuario user) {
        initComponents();
        this.conn=conn;
        this.user = user;
        cargarEspecialidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        equipoMedico1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fotoImg = new javax.swing.JLabel();
        especial = new javax.swing.JLabel();
        medicoComboBox = new javax.swing.JComboBox<>();
        especialidad1 = new javax.swing.JLabel();
        especialidadComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        comentarios = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        inicio = new javax.swing.JLabel();
        equipoMedico = new javax.swing.JLabel();
        preguntas_Frecuentes = new javax.swing.JLabel();
        agendarCita = new javax.swing.JLabel();
        historialClinico1 = new javax.swing.JLabel();
        historialClinico2 = new javax.swing.JLabel();
        historialCitas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipo Medico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(166, 213, 213));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO_ISSSTE.png"))); // NOI18N
        jLabel1.setInheritsPopupMenu(false);

        jPanel18.setBackground(new java.awt.Color(88, 153, 153));
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.setPreferredSize(new java.awt.Dimension(90, 35));

        cerrarSesion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        equipoMedico1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        equipoMedico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipoMedico1.setText("Dudas y contacto: atencionciudadana@issste.gob.mx o al 55-4000-1000");
        equipoMedico1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(equipoMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 657, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equipoMedico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1200, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opiniones equipo médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        fotoImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fotoImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fotoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fotoImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );

        especial.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        especial.setText("Especialidad");

        medicoComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        medicoComboBox.setBorder(null);
        medicoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoComboBoxActionPerformed(evt);
            }
        });

        especialidad1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        especialidad1.setText("Médico");

        especialidadComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        especialidadComboBox.setBorder(null);
        especialidadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadComboBoxActionPerformed(evt);
            }
        });

        comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(comentarios);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialidad1)
                            .addComponent(especial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(especialidadComboBox, 0, 249, Short.MAX_VALUE)
                            .addComponent(medicoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(especial)
                    .addComponent(especialidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(especialidad1)
                            .addComponent(medicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1100, 610));

        inicio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.setText("Inicio");
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });

        equipoMedico.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        equipoMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipoMedico.setText("Equipo Médico");
        equipoMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipoMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipoMedicoMouseClicked(evt);
            }
        });

        preguntas_Frecuentes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        preguntas_Frecuentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preguntas_Frecuentes.setText("Preguntas Frecuentes");
        preguntas_Frecuentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preguntas_Frecuentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preguntas_FrecuentesMouseClicked(evt);
            }
        });

        agendarCita.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        agendarCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agendarCita.setText("Agendar Cita");
        agendarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendarCitaMouseClicked(evt);
            }
        });

        historialClinico1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        historialClinico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialClinico1.setText("Crear Opinion");
        historialClinico1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialClinico1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialClinico1MouseClicked(evt);
            }
        });

        historialClinico2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        historialClinico2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialClinico2.setText("Perfil");
        historialClinico2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialClinico2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialClinico2MouseClicked(evt);
            }
        });

        historialCitas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        historialCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialCitas.setText("Historial de Citas");
        historialCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialCitasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preguntas_Frecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agendarCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialClinico1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialClinico2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 413, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(equipoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(preguntas_Frecuentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(agendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historialClinico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historialClinico2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historialCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        // TODO add your handling code here:
        Vista_Principal vistaP = new Vista_Principal(conn);
        vistaP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void especialidadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadComboBoxActionPerformed
        // TODO add your handling code here:
        cargarMedicosPorEspecialidad((String) especialidadComboBox.getSelectedItem());
    }//GEN-LAST:event_especialidadComboBoxActionPerformed

    private void medicoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoComboBoxActionPerformed
        // TODO add your handling code here
        cargarOpinionesDeMedico((Medico) medicoComboBox.getSelectedItem());
    }//GEN-LAST:event_medicoComboBoxActionPerformed

    private void equipoMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipoMedicoMouseClicked
        // TODO add your handling code here:
        Equipo_Medico equipo = new Equipo_Medico(conn, user);
        this.setVisible(false);
        equipo.setVisible(true);
    }//GEN-LAST:event_equipoMedicoMouseClicked

    private void preguntas_FrecuentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntas_FrecuentesMouseClicked
        // TODO add your handling code here:
        Preguntas_Frecuentes preguntas = new Preguntas_Frecuentes(conn,user);
        preguntas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_preguntas_FrecuentesMouseClicked

    private void agendarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarCitaMouseClicked
        AgendarCita agendar = new AgendarCita(user,conn);
        this.setVisible(false);
        agendar.setVisible(true);
    }//GEN-LAST:event_agendarCitaMouseClicked

    private void historialClinico1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialClinico1MouseClicked
        // TODO add your handling code here:
        Crear_Opinion opin = new Crear_Opinion(conn,user);
        this.setVisible(false);
        opin.setVisible(true);
    }//GEN-LAST:event_historialClinico1MouseClicked

    private void historialClinico2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialClinico2MouseClicked
        // TODO add your handling code here:
        Inicio_Usuario vistaU = new Inicio_Usuario(user,conn);
        this.setVisible(false);
        vistaU.setVisible(true);
    }//GEN-LAST:event_historialClinico2MouseClicked

    private void historialCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialCitasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Historial_De_Citas hist = new Historial_De_Citas(user, conn);
        hist.setVisible(true);
    }//GEN-LAST:event_historialCitasMouseClicked

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        Vista_Principal_Afiliado vp = new Vista_Principal_Afiliado(conn,user);
        this.setVisible(false);
        vp.setVisible(true);
    }//GEN-LAST:event_inicioMouseClicked

    private void fotoImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoImgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoImgMouseClicked
    
    public List<String> getAllEspecialidades() {
        List<String> especialidades = new ArrayList<>();
        String query = "SELECT DISTINCT especialidad FROM especialistas";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                especialidades.add(rs.getString("especialidad"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return especialidades;
    }
    public List<Medico> getMedicosByEspecialidad(String especialidad) {
        List<Medico> medicos = new ArrayList<>();
        String query = "SELECT id, nombre, especialidad, correo FROM especialistas WHERE especialidad = ?";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, especialidad);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                String correo = rs.getString("correo");
                medicos.add(new Medico(id, nombre, especialidad,correo));
                //System.out.println(correo);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return medicos;
    }
    
    private void cargarEspecialidades() {
        List<String> especialidades = getAllEspecialidades();
        especialidadComboBox.removeAllItems();
        for (String especialidad : especialidades) {
            especialidadComboBox.addItem(especialidad);
        }
        if (especialidades.size() > 0) {
            especialidadComboBox.setSelectedIndex(0); // Seleccionar la primera especialidad por defecto
        }
    }

    private void cargarMedicosPorEspecialidad(String especialidad) {
        medicoComboBox.removeAllItems();
        List<Medico> medicos = getMedicosByEspecialidad(especialidad);
        for (Medico medico : medicos) {
            medicoComboBox.addItem(medico);
        }
        if (medicos.size() > 0) {
            medicoComboBox.setSelectedIndex(0); // Seleccionar el primer médico por defecto
        }
    }

     private void cargarOpinionesDeMedico(Medico medico) {
        DefaultTableModel opinionesTableModel = new DefaultTableModel();
        opinionesTableModel.addColumn("Comentarios");
        comentarios.setModel(opinionesTableModel);
        if (medico != null) {
            List<String> opiniones = getOpinionesByMedico(medico.getId());
            for (String opinion : opiniones) {
                
                opinionesTableModel.addRow(new Object[]{opinion});
            }
            System.out.println(medico.getCorreo());
            
        String img = cargarImg(Registrar_Informe.getIdMedico2(conn, medico.getCorreo()));
        if(img!=null){
        Image foto = getToolkit().getImage(img);
        fotoImg.setIcon(new ImageIcon(foto));
        //System.out.print(img);
        }else{
            fotoImg.setIcon(null);
        }
        }
    }
     
    private String cargarImg(int idMedico){
        // Construir la sentencia SQL para obtener el nombre del usuario
        String nombre="";
        String sqlUsuario = "SELECT img FROM usuarios WHERE id = " + idMedico;
        // Crear la declaración y ejecutar la consulta
        try (Statement stmtUsuario = conn.createStatement();
             ResultSet rs = stmtUsuario.executeQuery(sqlUsuario)) {

            if (rs.next()) {
                nombre = rs.getString("img");
            } 
        } catch (SQLException e) {
            e.printStackTrace(); // Manejo adecuado de la excepción en tu aplicación
        }
        //System.out.println(nombre);
        return nombre;
    } 
     
    
    public List<String> getOpinionesByMedico(int medicoId) {
        List<String> opiniones = new ArrayList<>();
        String query = "SELECT opinion FROM opinionesequipomedico WHERE id_medico = ?";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setInt(1, medicoId);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                opiniones.add(rs.getString("opinion"));
                //System.out.print(opiniones.toString());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return opiniones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agendarCita;
    private javax.swing.JLabel cerrarSesion;
    private javax.swing.JTable comentarios;
    private javax.swing.JLabel equipoMedico;
    private javax.swing.JLabel equipoMedico1;
    private javax.swing.JLabel especial;
    private javax.swing.JLabel especialidad1;
    private javax.swing.JComboBox<String> especialidadComboBox;
    private javax.swing.JLabel fotoImg;
    private javax.swing.JLabel historialCitas;
    private javax.swing.JLabel historialClinico1;
    private javax.swing.JLabel historialClinico2;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Medico> medicoComboBox;
    private javax.swing.JLabel preguntas_Frecuentes;
    // End of variables declaration//GEN-END:variables
}
